//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByYoung.Butterfly.AutoGenerate
{ 
    public sealed class TranslaterDefine
    {
        
        [System.ComponentModel.DescriptionAttribute("操作类型")]
        public enum MsgTypes
        {
            
            Create_Player = 0,
            
            Create_Entity = 1,
            
            Move_Entity = 2,
            
            Lock_Target = 3,
            
            Entity_Attack = 4,
            
            Entity_GetHit = 5,
            
            BuffAction = 6,
            
            Entity_Dead = 7,
            
            Cancel_Bev = 8,
            
            Sync_PlayerHP = 9,
            
            Sync_Property = 10,
        }
    }
}
